Repository six-goguma/Algo-Hive-BE, pull requests merged in 2025-02, with the labels that each got.

#44 Refactor: 이메일 인증 메일 형식 수정, 리팩토링 및 api 문서 작업
  src/main/java/com/knu/algo_hive/auth/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
  src/main/java/com/knu/algo_hive/auth/controller/AuthRestController.java
  src/main/java/com/knu/algo_hive/auth/dto/LoginResponse.java
  src/main/java/com/knu/algo_hive/auth/service/CustomUserDetails.java
  src/main/java/com/knu/algo_hive/auth/service/MailService.java
  src/main/java/com/knu/algo_hive/auth/service/MemberService.java
  src/main/java/com/knu/algo_hive/common/annotation/ApiErrorCodeExample.java
  src/main/java/com/knu/algo_hive/common/annotation/ApiErrorCodeExamples.java
  src/main/java/com/knu/algo_hive/common/config/SwaggerConfig.java
  src/main/java/com/knu/algo_hive/common/exception/BadRequestException.java
  src/main/java/com/knu/algo_hive/common/exception/ConflictException.java
  src/main/java/com/knu/algo_hive/common/exception/ErrorCode.java
  src/main/java/com/knu/algo_hive/common/exception/ErrorResponseDto.java
  src/main/java/com/knu/algo_hive/common/exception/ExampleHolder.java
  src/main/java/com/knu/algo_hive/common/exception/ForbiddenException.java
  src/main/java/com/knu/algo_hive/common/exception/GlobalExceptionHandler.java
  src/main/java/com/knu/algo_hive/common/exception/NotFoundException.java
  src/main/java/com/knu/algo_hive/common/exception/UnauthorizedException.java
Labels: 📡 API, ♻️ Refactoring

#42 Feat: 좋아요 기능 구현
  src/main/java/com/knu/algo_hive/post/controller/LikeController.java
  src/main/java/com/knu/algo_hive/post/entity/Like.java
  src/main/java/com/knu/algo_hive/post/entity/Post.java
  src/main/java/com/knu/algo_hive/post/repository/LikeRepository.java
  src/main/java/com/knu/algo_hive/post/service/LikeService.java
Labels: ✨ Feature

#51 Feat: 채팅방별 접속자 수 조회가능 구현
  src/main/java/com/knu/algo_hive/chat/rabbitmq/UserStatusConsumer.java
  src/main/java/com/knu/algo_hive/chat/rabbitmq/UserStatusProducer.java
  src/main/java/com/knu/algo_hive/common/config/RabbitConfig.java
Labels: ✨ Feature

#54 Fix, Deploy : ErrorCode 파일 수정 및 배포 설정 변경
  .github/workflows/docker-push-deploy.yml
  k8s/deployment.yaml.template
  src/main/java/com/knu/algo_hive/common/exception/ErrorCode.java
Labels: 😡 Bug Fix, 📦 Environment

#55 HotFix : Credentials허용
  src/main/java/com/knu/algo_hive/common/config/WebConfig.java
Labels: 🚑 HotFix!

#57 bugfix : 레디스 연동
  build.gradle
  src/main/java/com/knu/algo_hive/auth/entity/Member.java
  src/main/resources/application.properties
Labels: 😡 Bug Fix

#58 refactor : 오탈자 수정
  src/main/java/com/knu/algo_hive/common/config/WebConfig.java
Labels: ♻️ Refactoring

#61 Refactor: 채팅방 및 채팅 불러오기 페이지네이션 처리
  src/main/java/com/knu/algo_hive/chat/controller/ChatController.java
  src/main/java/com/knu/algo_hive/chat/repository/ChatMessageRepository.java
  src/main/java/com/knu/algo_hive/chat/service/ChatMessageService.java
  src/main/java/com/knu/algo_hive/chat/service/RoomService.java
Labels: ♻️ Refactoring

#64 Feat: AI 분석 회원 연동 및 회원별 분석 결과 제공 API 구현
  src/main/java/com/knu/algo_hive/ai/controller/GeminiApiController.java
  src/main/java/com/knu/algo_hive/ai/dto/AiReportResponse.java
  src/main/java/com/knu/algo_hive/ai/entity/Gemini.java
  src/main/java/com/knu/algo_hive/ai/entity/GeminiRequestEntity.java
  src/main/java/com/knu/algo_hive/ai/entity/GeminiResponseEntity.java
  src/main/java/com/knu/algo_hive/ai/repository/GeminiRepository.java
  src/main/java/com/knu/algo_hive/ai/repository/GeminiRequestRepository.java
  src/main/java/com/knu/algo_hive/ai/repository/GeminiResponseRepository.java
  src/main/java/com/knu/algo_hive/ai/service/GeminiApiService.java
  src/main/java/com/knu/algo_hive/chat/controller/ChatController.java
Labels: ✨ Feature

#65 Feat: 이미지 관련 기능 구현
  src/main/java/com/knu/algo_hive/common/config/WebConfig.java
  src/main/java/com/knu/algo_hive/post/controller/CommentController.java
  src/main/java/com/knu/algo_hive/post/controller/ImageController.java
  src/main/java/com/knu/algo_hive/post/controller/LikeController.java
  src/main/java/com/knu/algo_hive/post/controller/PostController.java
  src/main/java/com/knu/algo_hive/post/controller/TagController.java
  src/main/java/com/knu/algo_hive/post/dto/CommentRequest.java
  src/main/java/com/knu/algo_hive/post/dto/CommentResponse.java
  src/main/java/com/knu/algo_hive/post/dto/ImageDeleteRequest.java
  src/main/java/com/knu/algo_hive/post/dto/ImageUploadRequest.java
  src/main/java/com/knu/algo_hive/post/dto/PostRequest.java
  src/main/java/com/knu/algo_hive/post/dto/PostResponse.java
  src/main/java/com/knu/algo_hive/post/dto/UrlResponse.java
  src/main/java/com/knu/algo_hive/post/service/CommentService.java
  src/main/java/com/knu/algo_hive/post/service/ImageService.java
  src/main/java/com/knu/algo_hive/post/service/PostService.java
  src/main/resources/application.properties
Labels: ✨ Feature

#66 refactor : 마이페이지, 인증 및 인가 기능 리팩토링
  build.gradle
  src/main/java/com/knu/algo_hive/auth/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
  src/main/java/com/knu/algo_hive/auth/controller/AuthRestController.java
  src/main/java/com/knu/algo_hive/auth/controller/MyPageController.java
  src/main/java/com/knu/algo_hive/auth/dto/LoginResponse.java
  src/main/java/com/knu/algo_hive/auth/dto/NickNameRequest.java
  src/main/java/com/knu/algo_hive/auth/dto/NicknameRequest.java
  src/main/java/com/knu/algo_hive/auth/dto/RegisterRequest.java
  src/main/java/com/knu/algo_hive/auth/entity/Member.java
  src/main/java/com/knu/algo_hive/auth/entity/Profile.java
  src/main/java/com/knu/algo_hive/auth/repository/MemberRepository.java
  src/main/java/com/knu/algo_hive/auth/service/MailService.java
  src/main/java/com/knu/algo_hive/auth/service/MemberService.java
  src/main/java/com/knu/algo_hive/auth/service/MyPageService.java
  src/main/java/com/knu/algo_hive/common/config/AsyncConfig.java
  src/main/java/com/knu/algo_hive/common/config/MailConfig.java
  src/main/java/com/knu/algo_hive/common/config/RedisConfig.java
  src/main/java/com/knu/algo_hive/common/exception/ErrorCode.java
  src/main/java/com/knu/algo_hive/common/properties/RedisProperties.java
  src/main/java/com/knu/algo_hive/post/repository/CommentRepository.java
  src/main/java/com/knu/algo_hive/post/repository/PostRepository.java
  src/main/java/com/knu/algo_hive/post/service/PostService.java
Labels: ♻️ Refactoring

#69 hotfix: cpu 코어 문제 해결
  src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
  src/main/java/com/knu/algo_hive/common/config/AsyncConfig.java
Labels: 🚑 HotFix!

#78 Feat: 채팅 Member연동 및 본인 식별 방식 전환
  src/main/java/com/knu/algo_hive/auth/service/MyPageService.java
  src/main/java/com/knu/algo_hive/chat/dto/ChatMessageInfo.java
  src/main/java/com/knu/algo_hive/chat/dto/ChatMessageRequest.java
  src/main/java/com/knu/algo_hive/chat/entity/ChatMessage.java
  src/main/java/com/knu/algo_hive/chat/repository/ChatMessageRepository.java
  src/main/java/com/knu/algo_hive/chat/service/ChatMessageService.java
Labels: ✨ Feature

#89 feat, refactor : 분산락 기능 다시 추가, spring security 경로 지정
  build.gradle
  src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
  src/main/java/com/knu/algo_hive/auth/service/MemberService.java
  src/main/java/com/knu/algo_hive/common/config/RedisConfig.java
  src/main/java/com/knu/algo_hive/common/properties/RedisProperties.java
Labels: ✨ Feature

#92 refactor : 이미지 관련 경로도 추가
  src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
Labels: ♻️ Refactoring

#93 bugfix: 리다이렉트 요청 제거
  src/main/java/com/knu/algo_hive/auth/config/CustomAuthenticationEntryPoint.java
Labels: 😡 Bug Fix
