Repository six-goguma/Algo-Hive-BE, pull requests merged in 2025-01, with the labels that each got.

#2 Deploy: 쿠버네티스, 깃액션, 도커 설정(CI/CD)
  .github/ISSUE_TEMPLATE/algo-hive-issue-template.md
  .github/pull_request_template.md
  .github/workflows/docker-push-and-deploy.yml 
  Dockerfile
  build.gradle
  k8s/deployment.yaml
  k8s/service.yaml
  src/main/java/com/knu/algo_hive/AlgoHiveApplication.java
  src/test/java/com/knu/algo_hive/AlgoHiveApplicationTests.java
Labels: 🚀 Deploy

#4 Feat: 도메인 h2-console, swagger-ui 경로 처리
  build.gradle
  src/main/java/com/knu/algo_hive/common/config/SwaggerConfig.java
  src/main/java/com/knu/algo_hive/common/controller/testController.java
  src/main/resources/application.properties
Labels: 🚀 Deploy, ✨ Feature

#10 Feat: gemini ai를 활용한 ai 기반 코드 분석 api 구현
  k8s/deployment.yaml.template
  src/main/java/com/knu/algo_hive/AlgoHiveApplication.java
  src/main/java/com/knu/algo_hive/ai/controller/GeminiApiController.java
  src/main/java/com/knu/algo_hive/ai/dto/GeminiApiRequest.java
  src/main/java/com/knu/algo_hive/ai/dto/GeminiApiResponse.java
  src/main/java/com/knu/algo_hive/ai/entity/GeminiRequestEntity.java
  src/main/java/com/knu/algo_hive/ai/entity/GeminiResponseEntity.java
  src/main/java/com/knu/algo_hive/ai/repository/GeminiRequestRepository.java
  src/main/java/com/knu/algo_hive/ai/repository/GeminiResponseRepository.java
  src/main/java/com/knu/algo_hive/ai/service/GeminiApiService.java
  src/main/java/com/knu/algo_hive/common/config/RestTemplateConfig.java
  src/main/java/com/knu/algo_hive/common/controller/TestController.java
Labels: ✨ Feature

#12 HotFix: 깃액션 빌드과정에서 gemini api key 환경변수로 추가
  .github/workflows/docker-push-deploy.yml
Labels: 🚑 HotFix!

#14 Feat: 인증/인가 api 명세서 구현
  src/main/java/com/knu/algo_hive/auth/controller/AuthRestController.java
  src/main/java/com/knu/algo_hive/auth/dto/EmailRequest.java
  src/main/java/com/knu/algo_hive/auth/dto/LoginRequest.java
  src/main/java/com/knu/algo_hive/auth/dto/NickNameRequest.java
  src/main/java/com/knu/algo_hive/auth/dto/RegisterRequest.java
  src/main/java/com/knu/algo_hive/auth/dto/VerificationRequest.java
Labels: 📡 API, ✨ Feature

#15 Feat: 게시물, 좋아요, 댓글, 태그 Swagger 명세
  src/main/java/com/knu/algo_hive/post/controller/CommentController.java
  src/main/java/com/knu/algo_hive/post/controller/LikeController.java
  src/main/java/com/knu/algo_hive/post/controller/PostController.java
  src/main/java/com/knu/algo_hive/post/controller/TagController.java
  src/main/java/com/knu/algo_hive/post/dto/CommentRequest.java
  src/main/java/com/knu/algo_hive/post/dto/CommentResponse.java
  src/main/java/com/knu/algo_hive/post/dto/LikeCountResponse.java
  src/main/java/com/knu/algo_hive/post/dto/LikeStatusResponse.java
  src/main/java/com/knu/algo_hive/post/dto/PostRequest.java
  src/main/java/com/knu/algo_hive/post/dto/PostResponse.java
  src/main/java/com/knu/algo_hive/post/dto/PostSummaryResponse.java
  src/main/java/com/knu/algo_hive/post/dto/TagRequest.java
  src/main/java/com/knu/algo_hive/post/dto/TagResponse.java
Labels: 📡 API

#17 Feat: 웹소켓을 이용한 채팅기능 구현
  .github/ISSUE_TEMPLATE/algo-hive-issue-template.md
  build.gradle
  src/main/java/com/knu/algo_hive/ai/controller/GeminiApiController.java
  src/main/java/com/knu/algo_hive/chat/entity/ChatMessage.java
  src/main/java/com/knu/algo_hive/chat/handler/ChatWebSocketHandler.java
  src/main/java/com/knu/algo_hive/chat/repository/ChatMessageRepository.java
  src/main/java/com/knu/algo_hive/common/config/WebConfig.java
  src/main/java/com/knu/algo_hive/common/config/WebSocketConfig.java
Labels: ✨ Feature

#19 Feat: pod 3개를 공유하기 위한 채팅 로직 수정
  .github/workflows/docker-push-deploy.yml
  build.gradle
  k8s/deployment.yaml.template
  src/main/java/com/knu/algo_hive/chat/controller/ChatController.java
  src/main/java/com/knu/algo_hive/chat/controller/WebSocketChatController.java
  src/main/java/com/knu/algo_hive/chat/dto/ChatMessageInfo.java
  src/main/java/com/knu/algo_hive/chat/dto/ChatMessageRequest.java
  src/main/java/com/knu/algo_hive/chat/dto/RoomRequest.java
  src/main/java/com/knu/algo_hive/chat/dto/RoomResponse.java
  src/main/java/com/knu/algo_hive/chat/dto/UserNameRequest.java
  src/main/java/com/knu/algo_hive/chat/entity/ChatMessage.java
  src/main/java/com/knu/algo_hive/chat/entity/Room.java
  src/main/java/com/knu/algo_hive/chat/handler/ChatWebSocketHandler.java
  src/main/java/com/knu/algo_hive/chat/rabbitmq/MessageConsumer.java
  src/main/java/com/knu/algo_hive/chat/rabbitmq/MessageProducer.java
  src/main/java/com/knu/algo_hive/chat/repository/ChatMessageRepository.java
  src/main/java/com/knu/algo_hive/chat/repository/RoomRepository.java
  src/main/java/com/knu/algo_hive/chat/service/ChatMessageService.java
  src/main/java/com/knu/algo_hive/chat/service/RoomService.java
  src/main/java/com/knu/algo_hive/common/config/RabbitConfig.java
  src/main/java/com/knu/algo_hive/common/config/WebConfig.java
  src/main/java/com/knu/algo_hive/common/config/WebSocketConfig.java
  src/main/java/com/knu/algo_hive/common/dto/StringTypeResponse.java
  src/main/resources/application.properties
Labels: 📡 API, ✨ Feature

#22 Feat: 전역 예외처리 advice 설정
  .gitignore
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/knu/.DS_Store
  src/main/java/com/knu/algo_hive/.DS_Store
  src/main/java/com/knu/algo_hive/chat/service/ChatMessageService.java
  src/main/java/com/knu/algo_hive/chat/service/RoomService.java
  src/main/java/com/knu/algo_hive/common/exception/BadRequestException.java
  src/main/java/com/knu/algo_hive/common/exception/ConflictException.java
  src/main/java/com/knu/algo_hive/common/exception/ForbiddenException.java
  src/main/java/com/knu/algo_hive/common/exception/GlobalExceptionHandler.java
  src/main/java/com/knu/algo_hive/common/exception/NotFoundException.java
  src/main/java/com/knu/algo_hive/common/exception/UnauthorizedException.java
Labels: ✨ Feature

#23 Feat : 인증/인가 기능 구현
  build.gradle
  src/main/java/com/knu/algo_hive/auth/config/SecurityConfig.java
  src/main/java/com/knu/algo_hive/auth/controller/AuthRestController.java
  src/main/java/com/knu/algo_hive/auth/entity/Member.java
  src/main/java/com/knu/algo_hive/auth/repository/MemberRepository.java
  src/main/java/com/knu/algo_hive/auth/service/CustomUserDetails.java
  src/main/java/com/knu/algo_hive/auth/service/MailService.java
  src/main/java/com/knu/algo_hive/auth/service/MemberService.java
  src/main/java/com/knu/algo_hive/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/knu/algo_hive/common/config/MailConfig.java
  src/main/java/com/knu/algo_hive/common/config/RedisConfig.java
  src/main/resources/application.properties
Labels: ✨ Feature

#25 Deploy: 도훈 작업물(세션 회원)에 서버 환경변수 작업
  .github/workflows/docker-push-deploy.yml
  k8s/deployment.yaml.template
Labels: 🚀 Deploy

#26 Feat: 게시물 관련 API 구현
  src/main/java/com/knu/algo_hive/post/controller/PostController.java
  src/main/java/com/knu/algo_hive/post/entity/Post.java
  src/main/java/com/knu/algo_hive/post/repository/PostRepository.java
  src/main/java/com/knu/algo_hive/post/service/PostService.java
  src/test/java/com/knu/algo_hive/post/repository/PostRepositoryTest.java
Labels: ✨ Feature

#29 Fix: 아직 미완성인 태그 관련 코드 주석화
  src/main/java/com/knu/algo_hive/post/controller/PostController.java
  src/main/java/com/knu/algo_hive/post/entity/Post.java
  src/main/java/com/knu/algo_hive/post/repository/PostRepository.java
  src/main/java/com/knu/algo_hive/post/service/PostService.java
Labels: 😡 Bug Fix

#31 HotFix: 배포시 실패하는 테스트 코드 제거
  src/test/java/com/knu/algo_hive/post/repository/PostRepositoryTest.java
Labels: 🚑 HotFix!

#33 Deploy: 메시지 브로커 변경으로 성능 개선
  build.gradle
  src/main/java/com/knu/algo_hive/chat/rabbitmq/MessageConsumer.java
  src/main/java/com/knu/algo_hive/chat/rabbitmq/MessageProducer.java
  src/main/java/com/knu/algo_hive/chat/repository/ChatMessageRepository.java
  src/main/java/com/knu/algo_hive/chat/service/ChatMessageService.java
  src/main/java/com/knu/algo_hive/common/config/RabbitConfig.java
  src/main/java/com/knu/algo_hive/common/config/WebSocketConfig.java
Labels: 🚀 Deploy

#35 Feat: 채팅방 접속자 목록 조회기능 구현
  src/main/java/com/knu/algo_hive/chat/controller/WebSocketChatController.java
  src/main/java/com/knu/algo_hive/chat/dto/UserInRoomResponse.java
  src/main/java/com/knu/algo_hive/chat/dto/UsersResponse.java
  src/main/java/com/knu/algo_hive/chat/rabbitmq/UserStatusConsumer.java
  src/main/java/com/knu/algo_hive/chat/rabbitmq/UserStatusProducer.java
  src/main/java/com/knu/algo_hive/common/config/RabbitConfig.java
Labels: ✨ Feature

#37 Deploy: userStatus set 인메모리 -> redis 사용으로 변경
  src/main/java/com/knu/algo_hive/chat/controller/WebSocketChatController.java
  src/main/java/com/knu/algo_hive/chat/dto/UsersResponse.java
  src/main/java/com/knu/algo_hive/chat/rabbitmq/UserStatusConsumer.java
  src/main/java/com/knu/algo_hive/chat/rabbitmq/UserStatusProducer.java
  src/main/java/com/knu/algo_hive/common/config/RabbitConfig.java
  src/main/java/com/knu/algo_hive/common/config/RedisConfig.java
  src/main/resources/application.properties
Labels: 🚀 Deploy

#41 Feat: 태그 기능 구현
  src/main/java/com/knu/algo_hive/post/controller/PostController.java
  src/main/java/com/knu/algo_hive/post/controller/TagController.java
  src/main/java/com/knu/algo_hive/post/dto/TagRequest.java
  src/main/java/com/knu/algo_hive/post/dto/TagResponse.java
  src/main/java/com/knu/algo_hive/post/entity/PostTag.java
  src/main/java/com/knu/algo_hive/post/entity/PostTagId.java
  src/main/java/com/knu/algo_hive/post/repository/PostRepository.java
  src/main/java/com/knu/algo_hive/post/repository/PostTagRepository.java
  src/main/java/com/knu/algo_hive/post/service/PostService.java
  src/main/java/com/knu/algo_hive/post/service/TagService.java
Labels: ✨ Feature

#46 Deploy: 컨테이너 및 스프링어플리케이션 실행 환경 시간 서울로 동기화
  Dockerfile
Labels: 🚀 Deploy
